name: linux

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
#        - '5.8'
#        - '5.10'
#        - '5.12'
#        - '5.14'
#        - '5.16'
#        - '5.18'
#        - '5.20'
#        - '5.22'
#        - '5.24'
#        - '5.26'
#        - '5.28'
        - '5.30'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
    - uses: actions/checkout@v2
    - run: env
    - run: perl -V
    - name: Add testsuite
      run: |
        make test-suite-data
    - name: Install deps
      run: >
        cpanm --quiet --notest
        Getopt::Long::Descriptive Test::More YAML::PP
    - name: Run Tests
      run: prove -lrv t
